// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using manhour_services.Data;

#nullable disable

namespace ManpowerControl.Migrations
{
    [DbContext(typeof(ManpowerContext))]
    [Migration("20240311091006_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("manhour_services.Models.ActivityName", b =>
                {
                    b.Property<string>("ActivityID")
                        .HasColumnType("text");

                    b.Property<string>("ActivityDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutomationCategory")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CategoryReasonIssue")
                        .HasColumnType("text");

                    b.Property<string>("FactoryID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feasibility")
                        .HasColumnType("text");

                    b.Property<string>("LineName")
                        .HasColumnType("text");

                    b.Property<string>("Pic")
                        .HasColumnType("text");

                    b.Property<string>("ProductModel")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SubCategoryDetail")
                        .HasColumnType("text");

                    b.HasKey("ActivityID");

                    b.ToTable("ActivityNames");
                });

            modelBuilder.Entity("manhour_services.Models.MhSaving", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ActivityID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<double>("MhSavingActual")
                        .HasColumnType("double precision");

                    b.Property<double>("MhSavingPlan")
                        .HasColumnType("double precision");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MhSavings");
                });

            modelBuilder.Entity("manhour_services.Models.StepProgress", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ActivityID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("StepProgressActual")
                        .HasColumnType("integer");

                    b.Property<int>("StepProgressPlan")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("StepProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
